site_name: Clinicians who code - The Opinionated Handbook
site_description: A handbook for clinicians who code
site_author: Clinicians who code

plugins:
  - search

theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    code: Roboto Mono

extra:
  generator: false


# Copyright information which is shown in the footer
copyright: Clinicians-who-code

# these lines configure the 'GitHub repo' widget on the top right
# uncomment to enable
repo_url: https://github.com/clinicians-who-code/clinicians-who-code-the-opinionated-handbook
repo_name: The handbook repository

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true
